service:
  service_name: "data-scraper"
  service_short_name: "dscrap"

aws:
  accounts:
    - &build "796717305864"

pipeline:
  account: *build
  region: "eu-north-1"
  repository_name: "data-scraper"
  repository_arn: "arn:aws:codecommit:eu-north-1:796717305864:data-scraper"

default_admin_users:
  - erik.manfredsson@vinnter.se

stages:
  dev:
    account: *build
    region: "eu-north-1"
  demo:
